### ISSUE TITLE
Target class [Jose\Component\Signature\Algorithm\HS256] does not exist.

### ISSUE THREAD

**Issue by tommica** [little-apps/LittleJWT#12]
Just did a fresh Laravel install, and wanted to use LittleJWT in it, but when I am trying to generate a JWT with `$jwt = Auth::buildJwtForUser($user);` I get this error message:

    Target class [Jose\Component\Signature\Algorithm\HS256] does not exist.

I could fix it by running `sail composer require web-token/jwt-signature-algorithm-hmac:^2.1`but I would imagine the package should handle this for me

**Comment by little-apps** [comment]
Thank you for filing this issue. The web-token/jwt-signature-algorithm-hmac package has been moved in the composer.json file so it's installed with both development and production installs. Developers wanting to use other JWT signature algorithms (ECDSA, RSA, etc.) will need to install the corresponding Composer package themselves (as mentioned in [the JWK documentation](https://docs.getlittlejwt.com/json-web-keys)).
